# Generated by Django 3.0.7 on 2020-06-23 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200623_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('sellete', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Seller')),
            ],
        ),
        migrations.AddField(
            model_name='basket',
            name='pickup_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Location'),
        ),
    ]
