# Generated by Django 3.0.7 on 2020-06-23 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_order_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='sellete',
            new_name='seller',
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Seller'),
        ),
    ]
