# Generated by Django 3.0.7 on 2020-06-23 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20200623_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Seller'),
        ),
    ]
