# Generated by Django 3.0.7 on 2020-07-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20200703_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basket',
            name='transaction_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
